### ISSUE TITLE
Parser crash on `assert by { } true` inside predicate

### ISSUE THREAD

**Issue by xtrm0** [dafny-lang/ide-vscode#118]
Valid dafny code, that causes the server to crash and no verification to happen:
```dafny
predicate DoesNotCrash()
{
  assert true; true
}

predicate Crashes()
{
  assert true by {
  } true
}
```

Output:
```
[Error - 4:15:50 PM] Request textDocument/documentSymbol failed.
  Message: Internal Error - System.Collections.Generic.KeyNotFoundException: The given key 'Microsoft.Dafny.BlockStmt' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.ProcessNestedScope(Object node, IToken token, Action visit) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 198
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.Visit(BlockStmt blockStatement) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 132
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(Statement statement) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 183
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.VisitNullableStatement(Statement statement) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 205
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(AssertStmt assertStatement) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 335
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(Statement statement) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 177
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(StmtExpr statementExpression) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 626
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(Expression expression) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 464
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(Function function) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 128
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.<>n__4(Function function)
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.<>c__DisplayClass17_0.<Visit>b__0() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 115
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.ProcessNestedScope(Object node, IToken token, Action visit) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 199
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.Visit(Function function) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 115
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(MemberDecl memberDeclaration) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 65
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(ClassDecl classDeclaration) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 49
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.<>n__1(ClassDecl classDeclaration)
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.<>c__DisplayClass13_0.<Visit>b__0() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 92
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.ProcessNestedScope(Object node, IToken token, Action visit) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 199
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.VisitTopLevelDeclarationWithMembers(TopLevelDeclWithMembers declaration, Action visit) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 104
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.Visit(ClassDecl classDeclaration) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 92
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(TopLevelDecl topLevelDeclaration) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 31
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(ModuleDefinition moduleDefinition) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 24
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.<>n__0(ModuleDefinition moduleDefinition)
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.<>c__DisplayClass12_0.<Visit>b__0() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 88
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.ProcessNestedScope(Object node, IToken token, Action visit) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 199
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.Visit(ModuleDefinition moduleDefinition) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 88
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(Program program) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 18
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.CreateFrom(Program program, CompilationUnit compilationUnit, CancellationToken cancellationToken) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 26
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.LoadInternal(LoadRequest loadRequest) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs:line 105
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.Run() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs:line 83
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.LoadAsync(TextDocumentItem textDocument, CancellationToken cancellationToken) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs:line 72
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.LoadAndVerifyAsync(TextDocumentItem textDocument, Boolean verify, CancellationToken cancellationToken) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs:line 86
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.OpenAndVerifyAsync(TextDocumentItem textDocument, CancellationToken cancellationToken) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs:line 77
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.GetDocumentAsync(TextDocumentIdentifier documentId) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs:line 170
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyDocumentSymbolHandler.Handle(DocumentSymbolParams request, CancellationToken cancellationToken) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Handlers/DafnyDocumentSymbolHandler.cs:line 34
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603 
```

**Comment by camrein** [comment]
Thanks a lot for reporting this bug. I suppose you're using the Dafny v3.3.0 that is shipped with the extension.
Fortunately, it appears to me that this bug is already fixed, most-likely with PR https://github.com/dafny-lang/dafny/pull/1630 by @MikaelMayer.
You may either want to wait for the release of Dafny v3.4.0 or compile Dafny from source by yourself.

**Comment by xtrm0** [comment]
Works with the new plugin and dafny 3.4.1
