### ISSUE TITLE
Exception on hover

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/ide-vscode#135]
I got this exception, I don't know how to reproduce it

```
[Error - 11:57:50 AM] Request textDocument/hover failed.
  Message: Internal Error - System.AggregateException: One or more errors occurred. (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.) (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.) (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.) (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.)
 ---> System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.Dafny.LanguageServer.Language.DiagnosticErrorReporter.AddDiagnosticForFile(Diagnostic item, DocumentUri documentUri) in dafny\Source\DafnyLanguageServer\Language\DiagnosticErrorReporter.cs:line 105
   at Microsoft.Dafny.LanguageServer.Language.DiagnosticErrorReporter.ReportBoogieError(ErrorInformation error) in dafny\Source\DafnyLanguageServer\Language\DiagnosticErrorReporter.cs:line 45
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.ModelCapturingOutputPrinter.WriteErrorInformation(ErrorInformation errorInfo, TextWriter tw, Boolean skipExecutionTrace) in dafny\Source\DafnyLanguageServer\Language\DafnyProgramVerifier.cs:line 235
   at Microsoft.Boogie.ExecutionEngine.ProcessErrors(List`1 errors, Outcome outcome, TextWriter tw, ErrorReporterDelegate er, Implementation impl)
   at Microsoft.Boogie.ExecutionEngine.VerifyImplementation(Program program, PipelineStatistics stats, ErrorReporterDelegate er, String requestId, Dictionary`2 extractLoopMappingInfo, Implementation[] stablePrioritizedImpls, Int32 index, OutputCollector outputCollector, CheckerPool checkerPool, String programId)
   at Microsoft.Boogie.ExecutionEngine.<>c__DisplayClass29_2.<InferAndVerify>b__5(Object dummy)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.Boogie.ExecutionEngine.InferAndVerify(Program program, PipelineStatistics stats, String programId, ErrorReporterDelegate er, String requestId)
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.VerifyWithBoogie(Program program, CancellationToken cancellationToken) in dafny\Source\DafnyLanguageServer\Language\DafnyProgramVerifier.cs:line 160
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.Verify(DafnyDocument document, CancellationToken cancellationToken) in dafny\Source\DafnyLanguageServer\Language\DafnyProgramVerifier.cs:line 134
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.VerifyInternal(VerifyRequest verifyRequest) in dafny\Source\DafnyLanguageServer\Workspace\TextDocumentLoader.cs:line 162
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.Run() in dafny\Source\DafnyLanguageServer\Workspace\TextDocumentLoader.cs:line 94
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.VerifyAsync(DafnyDocument document, CancellationToken cancellationToken) in dafny\Source\DafnyLanguageServer\Workspace\TextDocumentLoader.cs:line 156
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.LoadAndVerifyAsync(TextDocumentItem textDocument, Boolean verify, CancellationToken cancellationToken) in dafny\Source\DafnyLanguageServer\Workspace\DocumentDatabase.cs:line 89
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(DafnyDocument oldDocument, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken) in dafny\Source\DafnyLanguageServer\Workspace\DocumentDatabase.cs:line 115
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.<>c__DisplayClass18_0.<<UpdateDocumentAsync>b__0>d.MoveNext() in dafny\Source\DafnyLanguageServer\Workspace\DocumentDatabase.cs:line 104
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.<>c__DisplayClass18_0.<<UpdateDocumentAsync>b__0>d.MoveNext() in dafny\Source\DafnyLanguageServer\Workspace\DocumentDatabase.cs:line 104
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.GetDocumentAsync(TextDocumentIdentifier documentId) in dafny\Source\DafnyLanguageServer\Workspace\DocumentDatabase.cs:line 169
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyHoverHandler.Handle(HoverParams request, CancellationToken cancellationToken) in dafny\Source\DafnyLanguageServer\Handlers\DafnyHoverHandler.cs:line 29
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
 ---> (Inner Exception #1) System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.Dafny.LanguageServer.Language.DiagnosticErrorReporter.AddDiagnosticForFile(Diagnostic item, DocumentUri documentUri) in dafny\Source\DafnyLanguageServer\Language\DiagnosticErrorReporter.cs:line 105
   at Microsoft.Dafny.LanguageServer.Language.DiagnosticErrorReporter.ReportBoogieError(ErrorInformation error) in dafny\Source\DafnyLanguageServer\Language\DiagnosticErrorReporter.cs:line 45
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.ModelCapturingOutputPrinter.WriteErrorInformation(ErrorInformation errorInfo, TextWriter tw, Boolean skipExecutionTrace) in dafny\Source\DafnyLanguageServer\Language\DafnyProgramVerifier.cs:line 235
   at Microsoft.Boogie.ExecutionEngine.ProcessErrors(List`1 errors, Outcome outcome, TextWriter tw, ErrorReporterDelegate er, Implementation impl)
   at Microsoft.Boogie.ExecutionEngine.VerifyImplementation(Program program, PipelineStatistics stats, ErrorReporterDelegate er, String requestId, Dictionary`2 extractLoopMappingInfo, Implementation[] stablePrioritizedImpls, Int32 index, OutputCollector outputCollector, CheckerPool checkerPool, String programId)
   at Microsoft.Boogie.ExecutionEngine.<>c__DisplayClass29_2.<InferAndVerify>b__5(Object dummy)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---

  Code: -32603 
```

**Comment by cpitclaudel** [comment]
This is another case of https://github.com/dafny-lang/dafny/pull/1651, which was fixed by https://github.com/dafny-lang/dafny/pull/1662 ; the bug is fixed in 3.4.
