### ISSUE TITLE
VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code

### ISSUE THREAD

**Issue by lhf552004** [dafny-lang/ide-vscode#355]
### Dafny version

3.0.4

### What happened?

Hi, I couldn't install Dafny extension in VScode successfully.
The error is 

`
VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
`
The info about vscode is below:
`
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
`
Is there version confilct?

### What type of operating system are you experiencing the problem on?

Windows

**Comment by fabiomadge** [comment]
Can you describe the steps you took in install the extension?

**Comment by lhf552004** [comment]
Yes, I opened VSCode, and then clicked extension buttons on the left, then I input Dafny, and then I clicked "install" button.
But it failed.
![image](https://user-images.githubusercontent.com/10030850/219459027-5a1507b1-7e3a-4717-92dc-bf0e8fb2ccd6.png)

![image](https://user-images.githubusercontent.com/10030850/219459136-27a3a05d-1fb2-4022-9c2d-95cac3e5c697.png)

**Comment by fabiomadge** [comment]
Can you try
```
code --verbose --install-extension dafny-lang.ide-vscode
```
?

**Comment by lhf552004** [comment]
Sure. It seems not found. Weird. 
![image](https://user-images.githubusercontent.com/10030850/219466096-a1658dc1-ba7a-4181-9852-4a1993292c92.png)

**Comment by fabiomadge** [comment]
This looks like a VS code issue to me, but the full log might offer more insights.

**Comment by lhf552004** [comment]
Hi, it is solved. It's a network issue. I just switched to another network. It is solved.
Thanks
